# -----------------------------------------------
#  7. Data Visualization:
#  Objective: Visualize the word frequencies
#  using a visualization library.
# 
#  Tools/Resources: Examples of visualization 
#  libraries D3, Plotly, and Chart.JS.
#     D3, https://d3js.org/
#     Plotly, https://plotly.com/
#     Chart.JS, https://www.chartjs.org/
#     Google Charts, https://developers.google.com/chart/
# -----------------------------------------------
from __future__ import annotations

import json
from pathlib import Path


IN_JSON = Path("data/frequency/title_word_counts.json")
OUT_DIR = Path("data/viz")
OUT_HTML = OUT_DIR / "word_frequency_top50.html"

TOP_N = 50  # change to 25/100 if you want


HTML_TEMPLATE = """<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>Course Title Word Frequency (Top {top_n})</title>
  <style>
    body {{
      font-family: system-ui, -apple-system, Segoe UI, Roboto, Helvetica, Arial, sans-serif;
      margin: 24px;
      line-height: 1.4;
    }}
    .container {{
      max-width: 1100px;
      margin: 0 auto;
    }}
    .meta {{
      color: #444;
      margin-bottom: 12px;
    }}
    canvas {{
      background: #fff;
      border: 1px solid #eee;
      border-radius: 12px;
      padding: 12px;
    }}
    .controls {{
      display: flex;
      gap: 12px;
      align-items: center;
      margin: 12px 0 18px;
      flex-wrap: wrap;
    }}
    input[type="number"] {{
      width: 90px;
      padding: 6px 8px;
    }}
    button {{
      padding: 8px 10px;
      cursor: pointer;
      border-radius: 10px;
      border: 1px solid #ddd;
      background: #f7f7f7;
    }}
    button:hover {{
      background: #f0f0f0;
    }}
    code {{
      background: #f6f6f6;
      padding: 2px 6px;
      border-radius: 6px;
    }}
  </style>
</head>
<body>
  <div class="container">
    <h1>Course Title Word Frequency (Top <span id="topNLabel">{top_n}</span>)</h1>
    <p class="meta">
      Source: <code>{source}</code> (generated by <code>06_frequency.py</code>)
    </p>

    <div class="controls">
      <label>Show top N:
        <input id="topNInput" type="number" min="5" max="500" value="{top_n}" />
      </label>
      <button id="applyBtn">Apply</button>
      <button id="toggleScaleBtn">Toggle log scale</button>
    </div>

    <canvas id="barChart" height="120"></canvas>
  </div>

  <!-- Chart.js via CDN -->
  <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
  <script>
    // Data embedded by 07_visualization.py
    const FULL_DATA = {data_json};

    // FULL_DATA format: [{{word: "...", count: 123}}, ...] sorted by count desc.

    let chart = null;
    let useLogScale = false;

    function makeDataset(topN) {{
      const sliced = FULL_DATA.slice(0, topN);
      return {{
        labels: sliced.map(d => d.word),
        counts: sliced.map(d => d.count)
      }};
    }}

    function render(topN) {{
      const ctx = document.getElementById("barChart");
      const ds = makeDataset(topN);

      const config = {{
        type: "bar",
        data: {{
          labels: ds.labels,
          datasets: [{{
            label: "Word frequency",
            data: ds.counts,
            borderWidth: 1
          }}]
        }},
        options: {{
          responsive: true,
          plugins: {{
            legend: {{ display: true }},
            tooltip: {{
              callbacks: {{
                label: (context) => ` ${{context.parsed.y}} occurrences`
              }}
            }}
          }},
          scales: {{
            x: {{
              ticks: {{
                maxRotation: 70,
                minRotation: 40
              }}
            }},
            y: {{
              beginAtZero: true,
              type: useLogScale ? "logarithmic" : "linear",
              title: {{
                display: true,
                text: useLogScale ? "Count (log scale)" : "Count"
              }},
              ticks: {{
                // For log scale, hide non-integer-ish tick labels clutter
                callback: function(value) {{
                  if (!useLogScale) return value;
                  const v = Number(value);
                  // show only powers of 10-ish ticks for readability
                  if (v === 1 || v === 10 || v === 100 || v === 1000 || v === 10000) return v;
                  return "";
                }}
              }}
            }}
          }}
        }}
      }};

      if (chart) {{
        chart.destroy();
      }}
      chart = new Chart(ctx, config);

      document.getElementById("topNLabel").textContent = topN;
    }}

    // initial render
    render({top_n});

    // controls
    document.getElementById("applyBtn").addEventListener("click", () => {{
      const topN = Number(document.getElementById("topNInput").value) || {top_n};
      render(Math.max(5, Math.min(topN, FULL_DATA.length)));
    }});

    document.getElementById("toggleScaleBtn").addEventListener("click", () => {{
      useLogScale = !useLogScale;
      const topN = Number(document.getElementById("topNInput").value) || {top_n};
      render(Math.max(5, Math.min(topN, FULL_DATA.length)));
    }});
  </script>
</body>
</html>
"""


def main() -> None:
    if not IN_JSON.exists():
        raise FileNotFoundError(
            f"Missing word counts JSON: {IN_JSON}\n"
            "Run 06_frequency.py first."
        )

    OUT_DIR.mkdir(parents=True, exist_ok=True)

    data = json.loads(IN_JSON.read_text(encoding="utf-8"))

    # Basic validation
    if not isinstance(data, list) or not data:
        raise ValueError("Word frequency JSON is empty or not a list.")

    # Ensure sorted (desc count)
    data = sorted(data, key=lambda d: (-int(d["count"]), str(d["word"])))

    html = HTML_TEMPLATE.format(
        top_n=TOP_N,
        source=str(IN_JSON),
        data_json=json.dumps(data, ensure_ascii=False),
    )

    OUT_HTML.write_text(html, encoding="utf-8")
    print(f"[done] Wrote visualization HTML -> {OUT_HTML}")
    print("Open it in a browser (double-click in file explorer, or use VS Code 'Open with Live Server').")


if __name__ == "__main__":
    main()